//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/15/2017 10:07:43 PM
namespace TestGrill.Infrastructure.GrillServiceOData
{
    
    /// <summary>
    /// There are no comments for GrillMenuContext in the schema.
    /// </summary>
    public partial class GrillMenuContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new GrillMenuContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GrillMenuContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ISolutions.Assessment.Grill.Core", "TestGrill.Infrastructure.GrillServiceOData");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("TestGrill.Infrastructure.GrillServiceOData", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ISolutions.Assessment.Grill.Core.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for GrillMenus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GrillMenu> GrillMenus
        {
            get
            {
                if ((this._GrillMenus == null))
                {
                    this._GrillMenus = base.CreateQuery<GrillMenu>("GrillMenus");
                }
                return this._GrillMenus;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GrillMenu> _GrillMenus;
        /// <summary>
        /// There are no comments for GrillMenuItemQuantities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GrillMenuItemQuantity> GrillMenuItemQuantities
        {
            get
            {
                if ((this._GrillMenuItemQuantities == null))
                {
                    this._GrillMenuItemQuantities = base.CreateQuery<GrillMenuItemQuantity>("GrillMenuItemQuantities");
                }
                return this._GrillMenuItemQuantities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GrillMenuItemQuantity> _GrillMenuItemQuantities;
        /// <summary>
        /// There are no comments for GrillMenuItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GrillMenuItem> GrillMenuItems
        {
            get
            {
                if ((this._GrillMenuItems == null))
                {
                    this._GrillMenuItems = base.CreateQuery<GrillMenuItem>("GrillMenuItems");
                }
                return this._GrillMenuItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GrillMenuItem> _GrillMenuItems;
        /// <summary>
        /// There are no comments for GrillMenus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGrillMenus(GrillMenu grillMenu)
        {
            base.AddObject("GrillMenus", grillMenu);
        }
        /// <summary>
        /// There are no comments for GrillMenuItemQuantities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGrillMenuItemQuantities(GrillMenuItemQuantity grillMenuItemQuantity)
        {
            base.AddObject("GrillMenuItemQuantities", grillMenuItemQuantity);
        }
        /// <summary>
        /// There are no comments for GrillMenuItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGrillMenuItems(GrillMenuItem grillMenuItem)
        {
            base.AddObject("GrillMenuItems", grillMenuItem);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"ISolutions.Assessment.Grill.Core\" xmlns=\"http://schemas.microsoft.com" +
                "/ado/2009/11/edm\"><EntityType Name=\"GrillMenu\"><Key><PropertyRef Name=\"Id\" /></K" +
                "ey><Property Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Name\" " +
                "Type=\"Edm.String\" /><NavigationProperty Name=\"GrillMenuItemQuantity\" Relationshi" +
                "p=\"ISolutions.Assessment.Grill.Core.GrillMenu_GrillMenuItemQuantity_GrillMenuIte" +
                "mQuantity_Menu\" ToRole=\"GrillMenuItemQuantity_Menu\" FromRole=\"GrillMenu_GrillMen" +
                "uItemQuantity\" /></EntityType><EntityType Name=\"GrillMenuItemQuantity\"><Key><Pro" +
                "pertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" " +
                "/><Property Name=\"Quantity\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationPrope" +
                "rty Name=\"Menu\" Relationship=\"ISolutions.Assessment.Grill.Core.GrillMenu_GrillMe" +
                "nuItemQuantity_GrillMenuItemQuantity_Menu\" ToRole=\"GrillMenu_GrillMenuItemQuanti" +
                "ty\" FromRole=\"GrillMenuItemQuantity_Menu\" /><NavigationProperty Name=\"GrillMenuI" +
                "tem\" Relationship=\"ISolutions.Assessment.Grill.Core.GrillMenuItemQuantity_GrillM" +
                "enuItem\" ToRole=\"GrillMenuItem\" FromRole=\"GrillMenuItemQuantity\" /></EntityType>" +
                "<EntityType Name=\"GrillMenuItem\"><Key><PropertyRef Name=\"Id\" /></Key><Property N" +
                "ame=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.Stri" +
                "ng\" /><Property Name=\"Length\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"Width\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Duration\" Type=\"Edm" +
                ".Time\" Nullable=\"false\" /></EntityType><Association Name=\"GrillMenu_GrillMenuIte" +
                "mQuantity_GrillMenuItemQuantity_Menu\"><End Type=\"ISolutions.Assessment.Grill.Cor" +
                "e.GrillMenuItemQuantity\" Role=\"GrillMenuItemQuantity_Menu\" Multiplicity=\"*\" /><E" +
                "nd Type=\"ISolutions.Assessment.Grill.Core.GrillMenu\" Role=\"GrillMenu_GrillMenuIt" +
                "emQuantity\" Multiplicity=\"0..1\" /></Association><Association Name=\"GrillMenuItem" +
                "Quantity_GrillMenuItem\"><End Type=\"ISolutions.Assessment.Grill.Core.GrillMenuIte" +
                "mQuantity\" Role=\"GrillMenuItemQuantity\" Multiplicity=\"*\" /><End Type=\"ISolutions" +
                ".Assessment.Grill.Core.GrillMenuItem\" Role=\"GrillMenuItem\" Multiplicity=\"0..1\" /" +
                "></Association><EntityContainer Name=\"GrillMenuContext\" m:IsDefaultEntityContain" +
                "er=\"true\"><EntitySet Name=\"GrillMenus\" EntityType=\"ISolutions.Assessment.Grill.C" +
                "ore.GrillMenu\" /><EntitySet Name=\"GrillMenuItemQuantities\" EntityType=\"ISolution" +
                "s.Assessment.Grill.Core.GrillMenuItemQuantity\" /><EntitySet Name=\"GrillMenuItems" +
                "\" EntityType=\"ISolutions.Assessment.Grill.Core.GrillMenuItem\" /><AssociationSet " +
                "Name=\"GrillMenuItemQuantity_Menu\" Association=\"ISolutions.Assessment.Grill.Core." +
                "GrillMenu_GrillMenuItemQuantity_GrillMenuItemQuantity_Menu\"><End Role=\"GrillMenu" +
                "_GrillMenuItemQuantity\" EntitySet=\"GrillMenus\" /><End Role=\"GrillMenuItemQuantit" +
                "y_Menu\" EntitySet=\"GrillMenuItemQuantities\" /></AssociationSet><AssociationSet N" +
                "ame=\"GrillMenuItemQuantity_GrillMenuItem\" Association=\"ISolutions.Assessment.Gri" +
                "ll.Core.GrillMenuItemQuantity_GrillMenuItem\"><End Role=\"GrillMenuItemQuantity\" E" +
                "ntitySet=\"GrillMenuItemQuantities\" /><End Role=\"GrillMenuItem\" EntitySet=\"GrillM" +
                "enuItems\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></ed" +
                "mx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for ISolutions.Assessment.Grill.Core.GrillMenu in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("GrillMenus")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class GrillMenu : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new GrillMenu object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GrillMenu CreateGrillMenu(global::System.Guid ID)
        {
            GrillMenu grillMenu = new GrillMenu();
            grillMenu.Id = ID;
            return grillMenu;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for GrillMenuItemQuantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<GrillMenuItemQuantity> GrillMenuItemQuantity
        {
            get
            {
                return this._GrillMenuItemQuantity;
            }
            set
            {
                this._GrillMenuItemQuantity = value;
                this.OnPropertyChanged("GrillMenuItemQuantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<GrillMenuItemQuantity> _GrillMenuItemQuantity = new global::System.Data.Services.Client.DataServiceCollection<GrillMenuItemQuantity>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ISolutions.Assessment.Grill.Core.GrillMenuItemQuantity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("GrillMenuItemQuantities")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class GrillMenuItemQuantity : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new GrillMenuItemQuantity object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GrillMenuItemQuantity CreateGrillMenuItemQuantity(global::System.Guid ID, int quantity)
        {
            GrillMenuItemQuantity grillMenuItemQuantity = new GrillMenuItemQuantity();
            grillMenuItemQuantity.Id = ID;
            grillMenuItemQuantity.Quantity = quantity;
            return grillMenuItemQuantity;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Menu in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GrillMenu Menu
        {
            get
            {
                return this._Menu;
            }
            set
            {
                this._Menu = value;
                this.OnPropertyChanged("Menu");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private GrillMenu _Menu;
        /// <summary>
        /// There are no comments for GrillMenuItem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GrillMenuItem GrillMenuItem
        {
            get
            {
                return this._GrillMenuItem;
            }
            set
            {
                this._GrillMenuItem = value;
                this.OnPropertyChanged("GrillMenuItem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private GrillMenuItem _GrillMenuItem;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ISolutions.Assessment.Grill.Core.GrillMenuItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("GrillMenuItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class GrillMenuItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new GrillMenuItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="length">Initial value of Length.</param>
        /// <param name="width">Initial value of Width.</param>
        /// <param name="duration">Initial value of Duration.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GrillMenuItem CreateGrillMenuItem(global::System.Guid ID, int length, int width, global::System.TimeSpan duration)
        {
            GrillMenuItem grillMenuItem = new GrillMenuItem();
            grillMenuItem.Id = ID;
            grillMenuItem.Length = length;
            grillMenuItem.Width = width;
            grillMenuItem.Duration = duration;
            return grillMenuItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Length in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Length
        {
            get
            {
                return this._Length;
            }
            set
            {
                this.OnLengthChanging(value);
                this._Length = value;
                this.OnLengthChanged();
                this.OnPropertyChanged("Length");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Length;
        partial void OnLengthChanging(int value);
        partial void OnLengthChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Width;
        partial void OnWidthChanging(int value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.TimeSpan Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.TimeSpan _Duration;
        partial void OnDurationChanging(global::System.TimeSpan value);
        partial void OnDurationChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
